### ISSUE TITLE
Оформление репозитория

### ISSUE THREAD

**Issue by tshemsedinov** [Sasha-OS/LifeGame#1]
- [x] Добавить eslint и конфигурацию, лучше взять эту: [.eslintrc.json](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/.eslintrc.json)
- [x] Добавить `README.md` 1-2 страницы описания проекта и кода
- [x] Добавить лицензию, например MIT, свое имя используй настоящее 
- [x] Добавить `package.json` с зависимостями, тем же eslint. Пример: [package.json](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/package.json)

**Comment by Sasha-OS** [comment]
Done

**Comment by Sasha-OS** [comment]
Closed

**Comment by tshemsedinov** [comment]
"свое имя используй настоящее" в лицензии и readme @Sasha-OS

**Comment by Sasha-OS** [comment]
Name changed
